### ISSUE TITLE
PSPNet-Res101 parameter

### ISSUE THREAD

**Issue by jiyeooong** [OSVAI/Af-DCD#2]
Hi,
Thanks for your excellent work!

I would like to receive the model parameters and trains script file of PSPNet-Res101 used in paper Table 1. (b) experiment, PSPNet-Res101 -> DeepLabV3-Res18.

**Comment by jwfanDL** [comment]
Thank you for your interests in our paper.

The results in  Table 1. (b) experiments are conducted on MGD codebase (based on MMSegmentation), whose training crop size is 512*512. And the PSPNet-Res101 pretrained checkpoint is downloaded from MMSegmentation official website.

If you are interested in this experiment, you can simply modify MGD loss to ours in MGD repo.

**Comment by jiyeooong** [comment]
I can't find the PSP teacher model parameters trained with Cityscapes datasets. So, I trained it, but the performance is not as good as the 78.32% value written in your paper. Could you please give me the PSP model parameters? :)

**Comment by jwfanDL** [comment]
Hi, you can download the checkpoint in this website: https://github.com/open-mmlab/mmsegmentation/tree/main/configs/pspnet

**Comment by jiyeooong** [comment]
The site only provides parameters learned with the size of cityscapes 512X1024. I want to receive the parameters learned in 512X512. Since KD's performance of the teacher model is important for the same comparison, I would appreciate it if you could provide it to me by email. My email is wldud8946@gmail.com. thank you!!!
