### ISSUE TITLE
model's weight trained with datasets

### ISSUE THREAD

**Issue by yaoyuan10475** [OSVAI/Af-DCD#3]
Hello,
Thanks for your excellent work!

I'd like to debug your OmniContrastiveFeatureLoss and figure out the details. But I can't find the teacher model weights, such as deeplabv3_resnet101_camvid_best_model.pth. I would be extremely grateful if you could provide it. Or I didn't find it.

**Comment by jwfanDL** [comment]
Thank you for your interests in our paper.

I have updated README.md, which provides these teacher checkpoint links. 

Thanks again for pointing out this issue.
