### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by Ftiasch1** [OSVAI/Af-DCD#4]
Thanks to the authors for their contribution! However, during the reproduction process, I realised that some divisions of the test data were not provided, such as the PASCAL Voc dataset. Could the authors please provide a more comprehensive test division and the corresponding procedure?

**Comment by jwfanDL** [comment]
Hi, thank you for your interests in our work. I guess your concern is that you did not find test folder when unzipping PASCAL VOC dataset. This is because the division is provided by .txt file in folder dataset/list/voc. You can check this folder.
